### ISSUE TITLE
flock: unrecognized option '--verbose'

### ISSUE THREAD

**Issue by aero** [myplaceonline/posixcube#18]
Hi,

I tried posixcube on Ubuntu 14.04 LTS.
It seems that the flock command doesn't have '--verbose' option.

flock --verbose option starts to emerge at ubuntu 16.04 LTS's util-linux_2.27.1 ( http://manpages.ubuntu.com/manpages/xenial/man1/flock.1.html )

**Comment by kevgrig** [comment]
Thanks for the report. I had a commit pending which gets rid of `flock` anyway. I found there were multiple race conditions with `flock`, so since I was going back to a loop anyway, I thought it would be easier to just check `stderr` for the `flock` error messages and then try again.
