### ISSUE TITLE
Other Operating Systems

### ISSUE THREAD

**Issue by bfmartin** [myplaceonline/posixcube#22]
I run posixcube on OpenBSD, along with Linux.

Until recently, I was able to define a cube that overrides and replaces the built-in cube_operating_system. Some recent change has broken that. I'm guessing the execution of command-line-supplied cubes has been delayed.

Will you accept a PR that will add recognition for OpenBSD? This would involve:
- defining POSIXCUBE_OS_OPENBSD
- adding another option to "case $(uname -s)" inside cube_operating_system.

Thank you.

**Comment by kevgrig** [comment]
Yes, absolutely. Thanks.

**Comment by bfmartin** [comment]
Thanks. I'll get it ready.
