### ISSUE TITLE
"-l" option doesn't respect external cubes shebang line.

### ISSUE THREAD

**Issue by aero** [myplaceonline/posixcube#24]
Hi,

Recently, "-l" option had been added. 
https://github.com/myplaceonline/posixcube/commit/989f97c006ec601d7fdc2345838f9d77a1acff09

If one's own cubes script has "#/bin/bash" shebang line, posixcube doesn't respect it.
I guess bucuase It interpretes any cube_include(ed) external cubes script as vanilla bourn shell(posixcube.sh's shebang line shell) and cubes script written in bash grammer like " if [[ ... ]]" generates  syntax error( [[: not found ..)

```
TESTCASE

$ tree
.
├── _external
│   └── _external.sh
└── test
    └── test.sh


$ cat test/test.sh
#!/bin/bash

#echo $(cube_operating_system)
if cube_operating_system_has_flavor ${POSIXCUBE_OS_FLAVOR_FEDORA}; then
    echo "POSIXCUBE_OS_FLAVOR_FEDORA (RHEL, CentOS, Fedora)"
elif cube_operating_system_has_flavor ${POSIXCUBE_OS_FLAVOR_DEBIAN}; then
    echo "POSIXCUBE_IS_FLAVOR_DEBIAN (Debian, Ubuntu)"
else
    echo "FLAVOR UNKNOWN"
fi

if cube_operating_system_has_flavor ${POSIXCUBE_OS_FLAVOR_UBUNTU}; then
    echo "UBUNTU"
elif cube_operating_system_has_flavor ${POSIXCUBE_OS_FLAVOR_RHEL}; then
    echo "RHEL"
elif cube_operating_system_has_flavor ${POSIXCUBE_OS_FLAVOR_CENTOS}; then
    echo "CENTOS"
elif cube_operating_system_has_flavor ${POSIXCUBE_OS_FLAVOR_DEBIAN}; then
    echo "DEBIAN"
elif cube_operating_system_has_flavor ${POSIXCUBE_OS_FLAVOR_FEDORA}; then
    echo "FEDORA"
elif cube_operating_system_has_flavor ${POSIXCUBE_OS_FLAVOR_UNKNOWN}; then
    echo "UNKNOWN"
fi
echo $(cube_operating_system_version_major)
echo $(cube_operating_system_version_minor)

cube_include _external
echo $DIST
if [[ $DIST == Linux ]]; then
    echo "_external:Linux"
else
    echo "_external:UNKNOWN"
fi

$ cat _external/_external.sh
#!/bin/bash


OS=$(uname -s)
DIST=

if [[ $OS == Linux ]]; then
    DIST="${OS}"
else
    DIST="UNKOWN"
fi


$ posixcube.sh -l -U _external -c test
[Wed Oct 18 11:38:24 KST 2017] [myhost] Executing locally ...
[Wed Oct 18 11:38:24 KST 2017] [myhost] Started cube: test
POSIXCUBE_IS_FLAVOR_DEBIAN (Debian, Ubuntu)
UBUNTU
16
4
[Wed Oct 18 11:38:24 KST 2017] [myhost test.sh] Including _external cube...
../posixcube/posixcube.sh: 7: ../_external/_external.sh: [[: not found
UNKOWN
../posixcube/posixcube.sh: 31: /home/aero/posixcubes/test/test.sh: [[: not found
_external:UNKNOWN
[Wed Oct 18 11:38:24 KST 2017] [myhost test.sh] Finished cube: test
$


```

But remote mode with "-h remotehost" option has no problem with the same test.
(because default remote login shell is bash ??)

Local test with explicit bash shell designation also works well
```
bash posixcube.sh -l -U _external -c test
```

**Comment by bioradical** [comment]
Very interesting. i can't reproduce your test case I think because my /bin/sh is symlinked to bash, but I see your point. Can you please try this patch:

```
diff --git a/posixcube.sh b/posixcube.sh
index 1cf12e2..373225a 100755
--- a/posixcube.sh
+++ b/posixcube.sh
@@ -2689,7 +2689,7 @@ HEREDOC
       cube_echo "Executing locally ..."
       
       # shellcheck disable=SC1090
-      . ${p_localcubedir}/${p_script}
+      ${p_localcubedir}/${p_script}
     fi
 
     if [ "${p_wait_pids}" != "" ]; then

```

**Comment by kevgrig** [comment]
Very interesting. i can't reproduce your test case I think because my /bin/sh is symlinked to bash, but I see your point. Can you please try this patch:

```
diff --git a/posixcube.sh b/posixcube.sh
index 1cf12e2..373225a 100755
--- a/posixcube.sh
+++ b/posixcube.sh
@@ -2689,7 +2689,7 @@ HEREDOC
       cube_echo "Executing locally ..."
       
       # shellcheck disable=SC1090
-      . ${p_localcubedir}/${p_script}
+      ${p_localcubedir}/${p_script}
     fi
 
     if [ "${p_wait_pids}" != "" ]; then

```

**Comment by aero** [comment]
I tried your patch.
but same result.

Test environment
```
Ubuntu 16.04

$ ls -la /bin/sh
lrwxrwxrwx 1 root root 4 Feb 18  2016 /bin/sh -> dash
```

**Comment by kevgrig** [comment]
I reproduced this issue on Ubuntu. As you mentioned, the problem is that posixcube [sources](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#dot) all scripts, meaning that all scripts are interpreted by the shell that the parent posixcube execution runs under, no matter what the [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) lines in the scripts contain.

We could convert all sources to executions, but then all of the posixcube functions are unavailable. There is [no standardized mechanism](https://stackoverflow.com/a/29239838) to export functions in a parent script to be available to child scripts. Ubuntu's default `/bin/sh` symlinks to `dash`, and `dash` doesn't support [exporting functions](https://stackoverflow.com/questions/1885871/exporting-a-function-in-shell) like `bash`, `ksh`, or `zsh` do.

As you mentioned, running `posixcube` itself with `bash` works around the problem, although that's not very intuitive.

I added a commit which reads all of the shebang lines of cubes and included cubes and if they all use the same shebang line, then the parent script is executed with that shell instead of `/bin/sh`. This solves the problem in this issue, although I'm not sure what a more general solution is if the scripts use multiple different shells.

**Comment by aero** [comment]
I tested out the latest version.

Changed feature: "reads all of the shebang lines of cubes and included cubes and if they all use the same shebang line, then the parent script is executed with that shell instead of /bin/sh."

All mycube and _mysubcuble use "#!/bin/sh" shebang line.
Why are they executed with bash instead of sh ?

```
$ tree
.
├── _mysubcube
│    └── _mysubcube.sh
└── mycube
      └── mycube.sh

$ cat mycube/mycube.sh
#!/bin/sh

cube_include _mysubcube

echo "mycube shell"
ps -p $$

if [[ true ]]; then
    echo "mycube: bash"
fi


$ cat _mysubcube/_mysubcube.sh
#!/bin/sh

echo "_mysubcube shell:"
ps -p $$

if [[ true ]]; then
    echo "_mysubcube: bash"
fi



$ ../posixcube/posixcube.sh -u user -h myhost -U _mysubcube -c mycube
[2017. 10. 29. (일) 20:31:19 KST] Preparing hosts: myhost ...
[2017. 10. 29. (일) 20:31:19 KST] Completed preparation.
[2017. 10. 29. (일) 20:31:19 KST] Transferring files to hosts: myhost ...
[2017. 10. 29. (일) 20:31:20 KST] Completed transfers.
[2017. 10. 29. (일) 20:31:20 KST] [myhost] Executing on myhost ...
[Sun Oct 29 20:31:19 KST 2017] [user] Started cube: mycube
[Sun Oct 29 20:31:19 KST 2017] [user mycube.sh:3] Including _mysubcube cube...
_mysubcube shell:
  PID TTY          TIME CMD
29597 ?        00:00:00 bash
_mysubcube: bash
mycube shell
  PID TTY          TIME CMD
29597 ?        00:00:00 bash
mycube: bash
[Sun Oct 29 20:31:20 KST 2017] [user] Finished cube: mycube
```

**Comment by kevgrig** [comment]
@aero I added a new commit which applies the same logic for remote executions. However, your example uses `$SHELL` which [evaluates to the login shell, not the shell that's executing](https://stackoverflow.com/questions/3327013/how-to-determine-the-current-shell-im-working-on). You can use these scripts for your test:

```
$ cat mycube/mycube.sh 
#!/bin/bash

cube_include _mysubcube

echo "mycube shell: $(ps -p $$ -ocomm=)"
echo "_mysubcube shell: $CHILD_SHELL"
$ cat _mysubcube/_mysubcube.sh 
#!/bin/bash

CHILD_SHELL=$(ps -p $$ -ocomm=)
echo "shell in _mysubcube: $CHILD_SHELL"
```

**Comment by aero** [comment]
Hi
I tried out the updated version.

shebang line <-> execution shell relation table.



* Remote mode
```
                                               mycube    _mysubcube
mycube(#!/bin/sh),   _mysubcube(#!/bin/sh)         sh          sh
mycube(#!/bin/bash), _mysubcube(#!/bin/sh)       bash        bash
mycube(#!/bin/sh),   _mysubcube(#!/bin/bash)     bash        bash
mycube(#!/bin/bash), _mysubcube(#!/bin/bash)     bash        bash
```

* Local mode(linux)
```
                                               mycube    _mysubcube
mycube(#!/bin/sh),   _mysubcube(#!/bin/sh)         sh          sh
mycube(#!/bin/bash), _mysubcube(#!/bin/sh)       bash        bash
mycube(#!/bin/sh),   _mysubcube(#!/bin/bash)       sh          sh
mycube(#!/bin/bash), _mysubcube(#!/bin/bash)     bash        bash
```

* Local mode(Mac)

Mac OS X's cp command does not support "-u" option.
https://github.com/myplaceonline/posixcube/blob/master/posixcube.sh#L2755

error message.
```
cp: illegal option -- u
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
.
.
```

**Comment by kevgrig** [comment]
Thanks for the catch on the `cp` flags. I've removed [non-standard flags](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/cp.html).

Thank you for doing all of that testing. I see there's a difference in the third line, but I can't reproduce it. Can you try again and show the output?

```
$ cat mycube/mycube.sh 
#!/bin/sh

cube_include _mysubcube

echo "mycube shell: $(ps -p $$ -ocomm=)"
echo "_mysubcube shell: $CHILD_SHELL"
$ cat _mysubcube/_mysubcube.sh 
#!/bin/bash

CHILD_SHELL=$(ps -p $$ -ocomm=)
echo "shell in _mysubcube: $CHILD_SHELL"
$ posixcube.sh -l -U _mysubcube/ -c mycube/
[Sun Oct 29 19:54:53 PDT 2017] Auto-detecting non-standard shell /bin/bash
[Sun Oct 29 19:54:53 PDT 2017] [x270] Executing locally ...
[Sun Oct 29 19:54:53 PDT 2017] [x270] Started cube: mycube
[Sun Oct 29 19:54:53 PDT 2017] [x270 mycube.sh:3] Including _mysubcube cube...
shell in _mysubcube: bash
mycube shell: bash
_mysubcube shell: bash
[Sun Oct 29 19:54:53 PDT 2017] [x270] Finished cube: mycube
```

**Comment by aero** [comment]
It' my mistake.
I got the same results.

* Local mode
```
                                               mycube    _mysubcube
mycube(#!/bin/sh),   _mysubcube(#!/bin/sh)         sh          sh
mycube(#!/bin/bash), _mysubcube(#!/bin/sh)       bash        bash
mycube(#!/bin/sh),   _mysubcube(#!/bin/bash)     bash        bash
mycube(#!/bin/bash), _mysubcube(#!/bin/bash)     bash        bash
```

Thanks.

**Comment by kevgrig** [comment]
No problem, thanks for your help on this one!
