### ISSUE TITLE
How about changing remote cache directory name from ~/posixcube to ~/.posixcube or ~/.posixcube_cache ?

### ISSUE THREAD

**Issue by aero** [myplaceonline/posixcube#25]
How about changing remote cache directory name from ~/posixcube to ~/.posixcube or ~/.posixcube_cache ?

Everytime I login to remote server, I'm confused that ~/posixcube directroy is whether which i created or a program generated, :)

**Comment by kevgrig** [comment]
Good point. Please try commit 0afa661aa08048d584a70f3534df2ffaff1d6260

**Comment by aero** [comment]
Thanks.
It works well.
