### ISSUE TITLE
Typo in help message.

### ISSUE THREAD

**Issue by aero** [myplaceonline/posixcube#27]
https://github.com/myplaceonline/posixcube/blob/master/posixcube.sh#L166
`cubevar_app_y="$(printf '%s' "${cubevar_app_x}" | cmd2" || cube_check_return`
->
`cubevar_app_y="$(printf '%s' "${cubevar_app_x}" | cmd2)" || cube_check_return`

**Comment by kevgrig** [comment]
Fixed, thanks!

**Comment by aero** [comment]
README.md also needs to be fixed.

**Comment by kevgrig** [comment]
Oops, fixed, thanks.
