### ISSUE TITLE
Order of -S and -D flags matters

### ISSUE THREAD

**Issue by lunarnull** [myplaceonline/posixcube#31]
If the `-D` flag (with an appropriate argument) is present on the command line before the `-S` flag, everything works as expected.  But if we put `-S` before `-D`, the custom superuser command value is ignored and the default of `sudo` gets substituted in all functions that use `$cubevar_api_superuser`.  It is caused by `$cubevar_api_superuser` getting it's final value during the sequential flag parsing and using the contemporary value of `$cubevar_api_superuser_command`.

**Comment by kevgrig** [comment]
Fixed in 1cadb0e, thanks!
