### ISSUE TITLE
Shellcheck

### ISSUE THREAD

**Issue by ghost** [myplaceonline/posixcube#5]
I ran shellcheck on the posixcube.sh and the result is this: http://ix.io/1PQt

Obviously not all of these are bugs but some such as the non-posixy things in a bourne shell (for example `caller`) and unquoted variables should be addressed.

**Comment by kevgrig** [comment]
Thank you. I ran [`checkbashisms`](http://manpages.ubuntu.com/manpages/precise/man1/checkbashisms.1.html) but it only had a few warnings which were expected. All of the references to `caller` are wrapped in `if` blocks with `cube_command_exists caller`. The philosophy of posixcube is to allow non-POSIX styles, but they must be optional. I will check the other warnings, thank you.

**Comment by kevgrig** [comment]
Thank you, `shellcheck` is very useful. It found a few bugs and now `posixcube.sh` passes cleanly through it.

**Comment by ghost** [comment]
@kevgrig happy to help, I've found a lot of bugs in my own scripts when using it.
